#include<stdio.h>
#include<conio.h>
void main()
{
int a[3][3]={10,20,30,40,50,60,70,80,90};
clrscr();
printf("Value at a[0][0]=%d\n",a[0][0]);
printf("Value at a[0][1]=%d\n",a[0][1]);
printf("Value at a[0][2]=%d\n",a[0][2]);
printf("Value at a[1][0]=%d\n",a[1][0]);
printf("Value at a[1][1]=%d\n",a[1][1]);
printf("Value at a[1][2]=%d\n",a[1][2]);
printf("Value at a[2][0]=%d\n",a[2][0]);
printf("Value at a[2][1]=%d\n",a[2][1]);
printf("Value at a[2][2]=%d\n",a[2][2]);
getch();
}