#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("#####");
printf("\n#");
printf("\n#");
printf("\n####");
printf("\n#");
printf("\n#");

printf("\n BIG C");
printf("\n###############");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#");
printf("\n#################");
getch();
}