create table user1 (userid int,username varchar(20),pass varchar(15),mail varchar(30),gnd varchar(10),city varchar(30),country varchar(20))
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
insert into user1 values(1,'amit','samsung','nausheenanjum2022@gmail.com','female','Nagpur','India')
select * from user1